### ISSUE TITLE
Error with new issue page

### ISSUE THREAD

**Issue by thomasshaw85** [alvila/redmine_watchers_by_group#1]
I have installed the plugin by copying the directory into plugins folder and migrating the database. Once I restart redmine I get a 500 error on the new issue page.

I am using version 1.0.3

Processing IssuesController#new (for 10.55.8.41 at 2010-11-05 13:19:06) [GET]
  Parameters: {"project_id"=>"quote-engine", "action"=>"new", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/new

ActionView::TemplateError (No plugin called 'redmine_watchers_by_group' - please use the full name of a loaded plugin.) on line #24 of vendor/plugins/alvila-redmine_watchers_by_group-dd2310e/app/views/watchers/_multiselect_group.erb:
21:   <input type="submit" value="Unselect" onclick="return uncheckSome('issue[watcher_user_ids][]')" /> |
22:   <input type="submit" value="Select All" onclick="return checkAll('issue[watcher_user_ids][]')" /> |
23:   <input type="submit" value="Unselect All" onclick="return uncheckAll('issue[watcher_user_ids][]')" />
24: </p>
25: 
26: <% content_for :header_tags do %>
27:   <%= javascript_include_tag "watchers_multisel.js", :plugin => 'redmine_watchers_by_group' %>

```
vendor/plugins/alvila-redmine_watchers_by_group-dd2310e/app/views/watchers/_multiselect_group.erb:24
app/helpers/application_helper.rb:802:in `content_for'
vendor/plugins/alvila-redmine_watchers_by_group-dd2310e/app/views/watchers/_multiselect_group.erb:23
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/issues/_form.rhtml:40:in `_run_rhtml_app47views47issues47_form46rhtml_locals_f_form_object'
app/views/issues/new.rhtml:7:in `_run_rhtml_app47views47issues47new46rhtml'
app/helpers/application_helper.rb:702:in `labelled_tabular_form_for'
app/views/issues/new.rhtml:3:in `_run_rhtml_app47views47issues47new46rhtml'
app/controllers/issues_controller.rb:122
app/controllers/issues_controller.rb:121:in `new'
```

Rendering /opt/BitNami/redmine2/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by alvila** [comment]
Wrong folder, I'll modify the install instructions to compensate for this, but the folder for the plugin should be redmine_watchers_by_group

**Comment by alvila** [comment]
By the way, no need to migrate the database, just restart redmine.

**Comment by alvila** [comment]
How did you do the instalation? I tried using the command I gave and it works great.

**Comment by thomasshaw85** [comment]
Great, works fine now.

Thanks

**Comment by thomasshaw85** [comment]
I copied the folder from a downloaded zip file.

When I tried the method in the readme i had a socket connection error
