### ISSUE TITLE
Query functionality

### ISSUE THREAD

**Issue by thomasshaw85** [alvila/redmine_watchers_by_group#2]
Hi Alvila,

I have a query with the your new plugin.

If I add a user to a group and then create a new issue adding that group as a watcher. The user I added to the group is successfully selected.

Rather than adding a specific user to the group I wanted to add to the group via the project tab under groups. This would enable me to add all people of a certain role on a project to a group.

If I do this and then select the group as a watch on a new issue the user with the specified role in the groups are not added.

Should I be able to do this?

**Comment by alvila** [comment]
I am not sure if i understand what you want to do.

You want to add user to group on a per project basis? I don't see that option in our redmine(trunk). 

There is a different plugin called redmine_watchers_by_role which enables you to add role to group/users and enable this role to be in the selection box. If this is what you want. Unfortunately this one is not yet compatible with the watchers_by_group(working on it).
The link for this one is https://github.com/alvila/redmine_watchers_by_role 

If this is not what you want, specify your request further and I'll see what I can do about it, no problem modifying the plugin.

**Comment by thomasshaw85** [comment]
Thanks will take a look at the other plugin
